stroyRoom/main/urls.py
from django.urls import path

from .views import index, ShopLoginView, profile, ShopLogoutView, RegisterDoneView, RegisterUserView

app_name = 'main'

urlpatterns = [
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', ShopLoginView.as_view(), name='login'),
    path('accounts/logout/', ShopLogoutView.as_view(), name='logout'),
    path('', index, name='index'),
]

stroyRoom/stroyRoom/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.contrib.staticfiles.views import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stroyRoom/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .utilities import get_timestamp_path


class Category(models.Model):
    title = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    super_category = models.ForeignKey('self',
                                       on_delete=models.PROTECT, null=True, blank=True,
                                       verbose_name='Надкатегория')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, verbose_name='Категория')
    title = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изоброжение')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    stock = models.PositiveIntegerField(verbose_name='Остаток')
    available = models.BooleanField(default=True, verbose_name='Доступность')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.title


class UserProfile(AbstractUser):

    def __str__(self):
        return self.username

stroyRoom/main/forms.py
from django.contrib.auth import password_validation
from .models import UserProfile
from django.core.exceptions import ValidationError
from django import forms


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Введите тот же самый пароль ещё раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введённые пароли не совпадают', code='password_mismatch'
            )}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        return user

    class Meta:
        model = UserProfile
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')

stroyRoom/main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView

from .forms import RegisterUserForm
from .models import UserProfile


def index(request):
    return render(request, 'main/index.html')


class ShopLoginView(LoginView):
    template_name = 'main/login.html'


class ShopLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class RegisterUserView(CreateView):
    model = UserProfile
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


def profile(request):
    return render(request, 'main/profile.html')

stroyRoom/main/templates/layout/banner_area.html
{% load static %}

<section class="banner_area">
      <div class="container">
            <div class="single_banner">
              <div class="banner_item"><a href="#"></a><img src="{% static 'main/images/bg/banner6.jpg' %}" alt="tools"></div>
            </div>
            <div class="single_banner">
              <div class="banner_item"><a href="#"></a><img src="{% static 'main/images/bg/banner7.jpg' %}" alt="tools"></div>
            </div>
      </div>
    </section>

stroyRoom/main/templates/layout/basic.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="ie=edge" http-equiv="x-ua-compatible">
    <link rel="stylesheet" href="{% static 'main/css/main.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
  </head>
  <body>
   {% include "layout/header.html" %}
   {% block content %}
       <h2>content</h2>
   {% endblock %}
   {% include "layout/footer.html" %}
    <script src="https://kit.fontawesome.com/75974e6d57.js" crossorigin="anonymous"></script>
    <script src="{% static 'main/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'main/js/main.min.js' %}"></script>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
  </body>
</html>

stroyRoom/main/templates/layout/brand_list.html
{% load static %}

 <section class="brand_list">
      <div class="container owl-5 owl-carousel">
            <div class="brand_item"><a href="#"><img src="{% static 'main/images/brand/brand1.jpg' %}" alt="brand"></a></div>
            <div class="brand_item"><a href="#"><img src="{% static 'main/images/brand/brand2.jpg' %}" alt="brand"></a></div>
            <div class="brand_item"><a href="#"><img src="{% static 'main/images/brand/brand3.jpg' %}" alt="brand"></a></div>
            <div class="brand_item"><a href="#"><img src="{% static 'main/images/brand/brand4.jpg' %}" alt="brand"></a></div>
            <div class="brand_item"><a href="#"><img src="{% static 'main/images/brand/brand5.jpg' %}" alt="brand"></a></div>
            <div class="brand_item"><a href="#"><img src="{% static 'main/images/brand/brand1.jpg' %}" alt="brand"></a></div>
      </div>
    </section>

stroyRoom/main/templates/layout/categories_product_area.html
{% load static %}

<section class="categories_product_area">
      <div class="container">
        <div class="section_title">
          <h2>Popular Categories</h2>
        </div>
        <div class="product_container owl-3 owl-carousel">
              <div class="product_item">
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="#">
                          <img src="{% static 'main/images/featured/featured.jpg' %}" alt="">
                      </a>
                  </div>
                  <div class="product_content">
                    <h4>Tops & Sets</h4>
                    <ul>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                    </ul><a href="#">Show all</a>
                  </div>
                </div>
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="#">
                          <img src="{% static 'main/images/featured/featured1.jpg' %}" alt="">
                      </a>
                  </div>
                  <div class="product_content">
                    <h4>Tops & Sets</h4>
                    <ul>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                    </ul><a href="#">Show all</a>
                  </div>
                </div>
              </div>
              <div class="product_item">
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="#">
                          <img src="{% static 'main/images/featured/featured7.jpg' %}" alt="">
                      </a>
                  </div>
                  <div class="product_content">
                    <h4>Tops & Sets</h4>
                    <ul>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                    </ul><a href="#">Show all</a>
                  </div>
                </div>
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="#">
                          <img src="{% static 'main/images/featured/featured3.jpg' %}" alt="">
                      </a>
                  </div>
                  <div class="product_content">
                    <h4>Tops & Sets</h4>
                    <ul>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                    </ul><a href="#">Show all</a>
                  </div>
                </div>
              </div>
              <div class="product_item">
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="#">
                          <img src="{% static 'main/images/featured/featured5.jpg' %}" alt="">
                      </a>
                  </div>
                  <div class="product_content">
                    <h4>Tops & Sets</h4>
                    <ul>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                    </ul><a href="#">Show all</a>
                  </div>
                </div>
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="#">
                          <img src="{% static 'main/images/featured/featured6.jpg' %}" alt="">
                      </a>
                  </div>
                  <div class="product_content">
                    <h4>Tops & Sets</h4>
                    <ul>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                    </ul><a href="#">Show all</a>
                  </div>
                </div>
              </div>
              <div class="product_item">
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="#">
                          <img src="{% static 'main/images/featured/featured4.jpg' %}" alt="">
                      </a>
                  </div>
                  <div class="product_content">
                    <h4>Tops & Sets</h4>
                    <ul>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                    </ul><a href="#">Show all</a>
                  </div>
                </div>
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="#">
                          <img src="{% static 'main/images/featured/featured7.jpg' %}" alt="">
                      </a>
                  </div>
                  <div class="product_content">
                    <h4>Tops & Sets</h4>
                    <ul>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                      <li><a href="#">tank tops</a></li>
                    </ul><a href="#">Show all</a>
                  </div>
                </div>
              </div>
        </div>
      </div>
    </section>

stroyRoom/main/templates/layout/featured_product_area.html
{% load static %}

 <section class="featured_product_area">
      <div class="container">
        <div class="section_title">
          <h2>Featured products</h2>
        </div>
        <div class="product_container owl-3 owl-carousel">
              <div class="product_item">
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="product-details.html">
                          <img src="{% static 'main/images/product/product1.jpg'%}" alt="product">
                      </a>
                  </div>
                  <div class="product_content">
                    <p class="manufacture_product"><a href="#">Brand</a></p>
                    <h4><a href="product-details.html">Model</a></h4>
                    <div class="price_box">
                        <span class="old_price">$3.00</span>
                        <span class="current_price">$2.00</span>
                    </div>
                  </div>
                </div>
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="product-details.html">
                          <img src="{% static 'main/images/product/product2.jpg' %}" alt="product">
                      </a>
                  </div>
                  <div class="product_content">
                    <p class="manufacture_product"><a href="#">Brand</a></p>
                    <h4><a href="product-details.html">Model</a></h4>
                    <div class="price_box">
                        <span class="old_price">$3.00</span>
                        <span class="current_price">$2.00</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="product_item">
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="product-details.html">
                          <img src="{% static 'main/images/product/product3.jpg' %}" alt="product">
                      </a>
                  </div>
                  <div class="product_content">
                    <p class="manufacture_product"><a href="#">Brand</a></p>
                    <h4><a href="product-details.html">Model</a></h4>
                    <div class="price_box">
                        <span class="old_price">$3.00</span>
                        <span class="current_price">$2.00</span>
                    </div>
                  </div>
                </div>
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="product-details.html">
                          <img src="{% static 'main/images/product/product4.jpg' %}" alt="product">
                      </a>
                  </div>
                  <div class="product_content">
                    <p class="manufacture_product"><a href="#">Brand</a></p>
                    <h4><a href="product-details.html">Model</a></h4>
                    <div class="price_box">
                        <span class="old_price">$3.00</span>
                        <span class="current_price">$2.00</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="product_item">
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="product-details.html">
                          <img src="{% static 'main/images/product/product5.jpg' %}" alt="product">
                      </a>
                  </div>
                  <div class="product_content">
                    <p class="manufacture_product"><a href="#">Brand</a></p>
                    <h4><a href="product-details.html">Model</a></h4>
                    <div class="price_box">
                        <span class="old_price">$3.00</span>
                        <span class="current_price">$2.00</span>
                    </div>
                  </div>
                </div>
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="product-details.html">
                          <img src="{% static 'main/images/product/product6.jpg' %}" alt="product">
                      </a>
                  </div>
                  <div class="product_content">
                    <p class="manufacture_product"><a href="#">Brand</a></p>
                    <h4><a href="product-details.html">Model</a></h4>
                    <div class="price_box">
                        <span class="old_price">$3.00</span>
                        <span class="current_price">$2.00</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="product_item">
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="product-details.html">
                          <img src="{% static 'main/images/product/product7.jpg' %}" alt="product">
                      </a>
                  </div>
                  <div class="product_content">
                    <p class="manufacture_product"><a href="#">Brand</a></p>
                    <h4><a href="product-details.html">Model</a></h4>
                    <div class="price_box">
                        <span class="old_price">$3.00</span>
                        <span class="current_price">$2.00</span>
                    </div>
                  </div>
                </div>
                <div class="single_product">
                  <div class="product_thumb">
                      <a class="primary_img" href="product-details.html">
                          <img src="{% static 'main/images/product/product8.jpg' %}" alt="product">
                      </a>
                  </div>
                  <div class="product_content">
                    <p class="manufacture_product"><a href="#">Brand</a></p>
                    <h4><a href="product-details.html">Model</a></h4>
                    <div class="price_box">
                        <span class="old_price">$3.00</span>
                        <span class="current_price">$2.00</span>
                    </div>
                  </div>
                </div>
              </div>
        </div>
      </div>
</section>

stroyRoom/main/templates/layout/footer.html
{% load static %}

    <footer>
      <div class="footer_top">
        <div class="container">
          <div class="footer_contact_us">
            <div class="footer_logo"><a href="{% url 'main:index' %}"><img src="{% static 'main/images/logo/logo.png' %}" alt="logo"></a></div>
            <div class="footer_contact">
              <p>
                We are a team of designers and
                developers that create high quality Magento, Prestashop, Opencart...
              </p>
              <div class="support">
                <div class="support_icon"><img src="{% static 'main/images/icon/hotline.png' %}" alt="hotline"></div>
                <div class="support_text">
                  <p><span>Customer Support</span><a href="tel:+71231231234">+7(123)1231234</a></p>
                </div>
              </div>
            </div>
          </div>
          <div class="footer_subscribe">
            <h3>Subscribe newsletter to get update</h3>
            <div class="subscribe_form">
              <form>
                <input type="email" placeholder="Enter your email">
                <button type="submit">Subscribe</button>
              </form>
            </div>
            <p>We’ll never share your email address with a third-party.</p>
            <div class="footer_social">
              <ul>
                <li><a class="facebook" href="#"><i class="fab fa-facebook"></i></a></li>
                <li><a class="twitter" href="#"><i class="fab fa-twitter"></i></a></li>
                <li><a class="youtube" href="#"><i class="fab fa-youtube"></i></a></li>
                <li><a class="google" href="#"><i class="fab fa-google-plus-g"></i></a></li>
                <li><a class="instagram" href="#"><i class="fab fa-instagram"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="footer_menu">
            <h3>Information</h3>
            <div class="menu">
              <ul>
                <li><a href="#">Delivery</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Stores</a></li>
              </ul>
              <ul>
                <li><a href="#">Legal Notice</a></li>
                <li><a href="#">Payment</a></li>
                <li><a href="#">Sitemap</a></li>
                <li><a href="#">My account</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="footer_bottom">
        <div class="container">
          <div class="copyright_area">
            <p>Copyright &copy; 2021<a href="#">StroyRoom</a>All Right Reserved</p>
          </div>
          <div class="footer_payment"><a href="#"><img src="{% static 'main/images/icon/payment.png' %}" alt="payment"></a></div>
        </div>
      </div>
    </footer>

stroyRoom/main/templates/layout/header.html
{% load static %}

    <header class="header">
      <div class="header_top">
        <div class="container">
          <div class="logo"><a href="{% url 'main:index' %}"><img src="{% static 'main/images/logo/logo.png'%}" alt="logo"></a></div>
          <div class="main-menu">
            <div class="menu-items">
              <nav>
                <ul>
                  <li><a href="{% url 'main:index' %}">Home</a></li>
                  <li><a href="#">Shop</a></li>
                  <li><a href="#">Pages</a></li>
                  <li><a href="#">Contact Us</a></li>
                  <li><a href="#">Settings</a></li>
                    <li><a href="{% url 'admin:index' %}">admin</a></li>
                    {% if user.is_authenticated %}
                  <li><a href="{% url 'main:profile' %}">Profile</a></li>
                  <li><a href="{% url 'main:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'main:register' %}">Register</a></li>
                  <li><a href="{% url 'main:login' %}">Login</a></li>
                    {% endif %}
                </ul>
              </nav>
            </div>
            <div class="phone-support">
              <div class="support_icon"><img src="{% static 'main/images/icon/icon_phone.png' %}" alt="phone"></div>
              <div class="support_text">
                <p><span>Customer Support</span><a href="tel:+71234567890">+712345678</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="header_middle">
        <div class="container">
          <div class="categories_menu">
            <div class="categories_title">
              <h2>All Categories</h2>
            </div>
          </div>
          <div class="search_container">
            <form>
              <div class="search_box">
                <input type="text" placeholder="Search entire store here...">
                <button type="submit"></button>
              </div>
            </form>
          </div>
          <div class="cart_wishlist">
            <div class="wishlist_btn"><a href="#"><i class="icon-heart"></i></a><span class="wishlist_quantity">3</span></div>
            <div class="mini_cart"><a href="#"><span class="icon-cart">$67.00</span></a><span class="cart_quantity">2</span></div>
          </div>
        </div>
      </div>
      <div class="header_bottom">
        <div class="container">
          <nav class="main_nav">
            <ul id="main_menu">
              <li><a href="#">Stroy materialy</a>
                    <div class="sub_nav">
                      <ul>
                        <li><a href="#">item 1</a></li>
                        <li><a href="#">item 2</a></li>
                        <li><a href="#">item 3</a></li>
                        <li><a href="#">item 4</a></li>
                      </ul>
                    </div>
              </li>
              <li><a href="#">Otdelochny materialy</a>
                    <div class="sub_nav">
                      <ul>
                        <li><a href="#">item 5</a></li>
                        <li><a href="#">item 6</a></li>
                        <li><a href="#">item 7</a></li>
                        <li><a href="#">item 8</a></li>
                      </ul>
                    </div>
              </li>
              <li><a href="#">Instruments</a>
                    <div class="sub_nav">
                      <ul>
                        <li><a href="#">item 9</a></li>
                        <li><a href="#">item 10</a></li>
                        <li><a href="#">item 11</a></li>
                        <li><a href="#">item 12</a></li>
                      </ul>
                    </div>
              </li>
              <li><a href="#">Electro Instruments</a>
                    <div class="sub_nav">
                      <ul>
                        <li><a href="#">item 13</a></li>
                        <li><a href="#">item 14</a></li>
                        <li><a href="#">item 15</a></li>
                        <li><a href="#">item 16</a></li>
                      </ul>
                    </div>
              </li>
              <li><a href="#">Santehnika</a>
                    <div class="sub_nav">
                      <ul>
                        <li><a href="#">item 17</a></li>
                        <li><a href="#">item 18</a></li>
                        <li><a href="#">item 19</a></li>
                        <li><a href="#">item 20</a></li>
                      </ul>
                    </div>
              </li>
              <li><a href="#">Electrica</a>
                    <div class="sub_nav">
                      <ul>
                        <li><a href="#">item 21</a></li>
                        <li><a href="#">item 22</a></li>
                        <li><a href="#">item 23</a></li>
                        <li><a href="#">item 24</a></li>
                      </ul>
                    </div>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    <div class="breadcrumb">
          <div class="container">
            <div class="breadcrumb_content">
              <ul>
                <li><a href="{% url 'main:index' %}">home</a></li>
                <li>breadcrumb</li>
              </ul>
            </div>
          </div>
        </div>
    </header>

stroyRoom/main/templates/layout/shipping_area.html
<section class="shipping_area">
      <div class="container">
            <div class="shipping_item">
              <div class="shipping_icon"><i class="fas fa-truck"></i></div>
              <div class="shipping_content">
                <h3>Free shipping on order</h3>
              </div>
            </div>
            <div class="shipping_item">
              <div class="shipping_icon"><i class="fas fa-phone"></i></div>
              <div class="shipping_content">
                <h3>Contact us 24 hrs a day</h3>
              </div>
            </div>
            <div class="shipping_item">
              <div class="shipping_icon"><i class="far fa-paper-plane"></i></div>
              <div class="shipping_content">
                <h3>You have 30 days to return</h3>
              </div>
            </div>
            <div class="shipping_item">
              <div class="shipping_icon"><i class="fas fa-credit-card"></i></div>
              <div class="shipping_content">
                <h3>100% secure payment</h3>
              </div>
            </div>
      </div>
    </section>

stroyRoom/main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block title %}
    Main Page
{% endblock %}

{% block content %}
    {% include 'layout/brand_list.html' %}
    {% include 'layout/banner_area.html' %}
    {% include 'layout/product_area.html' %}
    {% include 'layout/categories_product_area.html' %}
    {% include 'layout/featured_product_area.html' %}
    {% include 'layout/shipping_area.html' %}
{% endblock %}

stroyRoom/main/templates/main/logout.html
{% extends 'layout/basic.html' %}

{% block title %}
    Выход
{% endblock %}

{% block content %}
    <h2>Выход</h2>
{% endblock %}

stroyRoom/main/templates/main/profile.html
{% extends 'layout/basic.html' %}

{% block title %}
    Профиль пользователя
{% endblock %}

{% block content %}
    <h2>Профиль пользователя {{ user.username }}</h2>
{% endblock %}